### PR TITLE
Attempt to fix brokenness with nbclassic override.

### PR DESCRIPTION
**Pull request by vwbusguy**
Please wait to see if passes before merging on this one, Brian :-)

### CODE REVIEW

**Comment by ParadoxGuitarist** [comment]
This might not be you: 
image

**Comment by ParadoxGuitarist** [comment]
Per the logs, looks like we might need `pip install notebook`

**Comment by vwbusguy** [comment]
https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1647

https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/issues/165

These were ported over from a legacy image.  At some point might be worth seeing what is still needed here.

It looks like there's a PR that might remedy this that's still waiting to be reviewed: https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/166

**Comment by ParadoxGuitarist** [comment]
I'm not sure how they're missing notebook being installed. It's possible they're looking in an old path.

**Comment by vwbusguy** [comment]
Pretty much.  Instead of "notebook", it needs to look to server now: https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/pull/166/files

**Pull request closed without merging**
